
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '3659CE35F8520F5AC3422755DFBABA33'
    
_lr_action_items = {'$end':([1,2,3,5,11,12,13,14,15,],[-7,-6,-3,0,-5,-4,-8,-2,-1,]),'RPAREN':([1,2,3,8,11,12,13,14,15,],[-7,-6,-3,13,-5,-4,-8,-2,-1,]),'MINUS':([1,2,3,5,8,11,12,13,14,15,],[-7,-6,-3,9,9,-5,-4,-8,-2,-1,]),'TIMES':([1,2,3,11,12,13,14,15,],[-7,-6,7,-5,-4,-8,7,7,]),'LPAREN':([0,4,6,7,9,10,],[4,4,4,4,4,4,]),'DIVIDE':([1,2,3,11,12,13,14,15,],[-7,-6,6,-5,-4,-8,6,6,]),'ICONST':([0,4,6,7,9,10,],[1,1,1,1,1,1,]),'PLUS':([1,2,3,5,8,11,12,13,14,15,],[-7,-6,-3,10,10,-5,-4,-8,-2,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[5,8,]),'factor':([0,4,6,7,9,10,],[2,2,11,12,2,2,]),'term':([0,4,9,10,],[3,3,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',51),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',55),
  ('expression -> term','expression',1,'p_expression_term','parser.py',59),
  ('term -> term TIMES factor','term',3,'p_term_times','parser.py',63),
  ('term -> term DIVIDE factor','term',3,'p_term_div','parser.py',67),
  ('term -> factor','term',1,'p_term_factor','parser.py',71),
  ('factor -> ICONST','factor',1,'p_factor_num','parser.py',75),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','parser.py',79),
]
